### ISSUE TITLE
adding/deleting multiple words at once

### ISSUE THREAD

**Issue by touretzkyds** [touretzkyds/WordEmbeddingDemo#51]
To save time, it would be helpful if the user could type multiple words in the Add/Remove Word text box, separated by spaces and/or commas, and have all of them processed at once. We should display an appropriate confirmation message, e.g.,
````
"cat", "dog", "fish" added. "alligator" removed. "paraqueet", "marmaset" not found.
````

**Comment by touretzkyds** [comment]
Note that if we have multiple words, some might be additions and some deletions. The "active" word should be the first word that is an addition. If there are no additions then deactivate any currently active word.

**Comment by neelpawarcmu** [comment]
We are currently supporting words separated by spaces, commas, full stops, semi-colons

**Comment by neelpawarcmu** [comment]
Resolved

**Comment by neelpawarcmu** [comment]
Resolved the bug where if we had for eg. fox fox added and removed simultaneously, the highlighting did not handle it earlier. Now we use a set to keep track of net added words and decides the same accordingly

**Comment by touretzkyds** [comment]
Still not resolved. Try this input: "fish sticks fish fry".

It correctly adds and removes "fish" but leaves the similarity display active.

**Comment by neelpawarcmu** [comment]
Sorry about the bugs. In such a case, what would correct behavior be? I was thinking in the case of "fish sticks fish fry", we could keep sticks ie., the first valid word active

**Comment by touretzkyds** [comment]
I would say we should keep the last word added, not the first one. Giving a list of words should produce the same behavior as if we had entered the words sequentially.
The problem is that the label says "Similarity to fish", not "Similarity to fry".

**Comment by neelpawarcmu** [comment]
Got it, I believe I have this implemented. I was reading off the wrong array which was leading to that behavior. I tested this now with quite a few different test cases, it showed expected behavior.

**Comment by touretzkyds** [comment]
Works great now!
